---
regions_to_exclude:
  - 'us-east-2'
  - 'us-west-1'
  - 'us-west-2'
  - 'ca-central-1'
  - 'ap-south-1'
  - 'ap-northeast-1'
  - 'ap-northeast-2'
  - 'ap-southeast-1'
  - 'ap-southeast-2'
  - 'eu-central-1'
  - 'eu-west-1'
  - 'eu-west-2'
  - 'sa-east-1'
checks_to_exclude:
  - ebs-snapshots
profiles:
  - default